version: '3.8'

services:
  web:
    build: .
    # Используем переменную окружения для динамического имени контейнера
    container_name: ${PROJECT_NAME}
    # Команда для запуска Gunicorn через Poetry.
    # Убедитесь, что 'myproject.wsgi:application' соответствует пути к вашему wsgi.py.
    command: poetry run gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - .env # Может быть пустым или удален, если нет других переменных
    # Зависимость от базы данных удалена, так как её нет

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
      -
volumes:
  static_volume:
  media_volume: