version: '3.8'

services:
  web:
    build: .
    # Используем переменную окружения для динамического имени контейнера
    container_name: ${PROJECT_NAME}
    # Команда для запуска Gunicorn через Poetry.
    # Убедитесь, что 'myproject.wsgi:application' соответствует пути к вашему wsgi.py.
    command: poetry run gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - 8000
    env_file:
      - .env # Может быть пустым или удален, если нет других переменных
    # Зависимость от базы данных удалена, так как её нет

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/tgup.su/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/tgup.su/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: