version: '3.8'

services:
  web:
    build: .
    # Используем переменную окружения для динамического имени контейнера
    container_name: ${PROJECT_NAME}
    # Команда для запуска Gunicorn через Poetry.
    # Убедитесь, что 'core.wsgi:application' соответствует пути к вашему wsgi.py.
    command: poetry run gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

  db:
    image: postgres:13-alpine
    container_name: ${PROJECT_NAME}_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
  static_volume:
  media_volume: